### ISSUE TITLE
嗨，你用的mitmproxy版本多少的呢

### ISSUE THREAD

**Issue by cong-long** [Strikersb/Wscanner#1]
我的报错了
    from mitmproxy import controller, options, master
ImportError: cannot import name master

版本：
mitmproxy (0.18.3)

你能不能给出一个模块列表对应使用的版本requirements.txt文件

**Comment by Strikersb** [comment]
mitmproxy是1.0.1版本，当时写这个代码的时候刚好mitmproxy更新了一个大版本= =
